# Generated by Django 6.1.1 on 2026-09-28 13:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contacts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone', models.CharField(help_text='Укажите номер телефона', max_length=50, verbose_name='Телефон')),
                ('email', models.EmailField(help_text='Укажите контактную почту', max_length=254, verbose_name='Email')),
                ('address', models.TextField(help_text='Укажите физический адрес организации', verbose_name='Адрес')),
            ],
            options={
                'verbose_name': 'Контактные данные',
                'verbose_name_plural': 'Контактные данные',
            },
        ),
    ]
